name: "Binance Spot Signals (WebSocket)"
version: "1.7.1"
slug: "binance_spot_signals_ws"
description: "Async Binance WebSocket signals bot (1h/15m/5m) with Telegram alerts. Raspberry Pi 5 ready."
arch:
  - aarch64
  - armv7
  - amd64
stage: experimental
startup: services
init: false
boot: auto
map:
  - addon_config:rw
  - share:rw

options:
  symbols: ["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT"]
  timezone: "Asia/Seoul"
  vwap_session_reset: "00:00"
  cooldown_minutes_per_symbol: 10
  one_signal_per_bar: true
  send_startup_message: true
  log_level: "INFO"
  long_only: true

  preset: "balanced"

  confirmations_min: 3
  rsi1h_block: 50
  volume_spike_mult: 1.5
  upper_wick_atr_block: 0.6

  ema_fast_1h: 20
  ema_slow_1h: 50
  ema_200_15m: 200
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  rsi_period: 14
  rsi_zone_low: 40
  rsi_zone_mid: 50
  rsi_zone_high: 60
  atr_period: 14
  vol_sma_period: 20

  atr_sl_mult: 1.3
  tp_multipliers: [0.5, 1.0, 1.5]
  atr_trailing_mult: 0.8
  use_vwap_trailing: true

  tg_token: ""
  tg_chat_id: ""

  symbol_overrides:
    BTCUSDT: { confirmations_min: 4 }
    XRPUSDT: { confirmations_min: 4, volume_spike_mult: 1.7, atr_sl_mult: 1.6 }
    SOLUSDT: { require_macd_and_rsi: true, atr_sl_mult: 1.4 }

schema:
  symbols:
    - str
  timezone: str
  vwap_session_reset: str
  cooldown_minutes_per_symbol: int
  one_signal_per_bar: bool
  send_startup_message: bool
  log_level: str
  long_only: bool
  preset: list(conservative|balanced|active)
  confirmations_min: int
  rsi1h_block: int
  volume_spike_mult: float
  upper_wick_atr_block: float
  ema_fast_1h: int
  ema_slow_1h: int
  ema_200_15m: int
  macd_fast: int
  macd_slow: int
  macd_signal: int
  rsi_period: int
  rsi_zone_low: int
  rsi_zone_mid: int
  rsi_zone_high: int
  atr_period: int
  vol_sma_period: int
  atr_sl_mult: float
  tp_multipliers:
    - float
  atr_trailing_mult: float
  use_vwap_trailing: bool
  tg_token: password
  tg_chat_id: str
  symbol_overrides: dict
