universe:
  quote: "USDT"
  min_vol_24h_usd: 5000000
  min_vol_15m_usd: 50000
  max_spread_pct: 0.15

timeframes:
  bias_tf: "1h"
  setup_tf: "15m"
  trigger_tf: "5m"

indicators:
  ema: [20, 50, 200]
  rsi: 14
  atr: 14
  vwap_session_reset_kst: true

bias:
  rsi_min: 50
  require_price_above_vwap_day_minus_sigma: 1.0
  ema_order: ["ema20>=ema50"]
  allow_if_price_above_ema200_15m: true

setup:
  base_window_bars_min: 8
  base_window_bars_max: 24
  atr14_percentile_max: 0.35
  rs_zscore_1h_min: 0.5
  need_prior_drop: true
  min_dist_below_ema20_5m_pct: 0.6

trigger:
  confirmations_needed: 3
  conditions:
    close_above_ema20: true
    close_above_vwap_and_vwap_rising: true
    macd:
      use: true
      hist_rising_bars_min: 2
      cross_up_allowed: true
    rvol15m_min: 1.6
    broke_local_high_lookback_bars: 10
  anti_noise:
    breakout_body_max_atr_mult: 1.8
    ema200_5m_min_distance_pct: 0.2
    rsi5m_overbought_for_retest:
      rsi: 78
      dist_from_ema20_atr_mult: 1.2

entries:
  mode: ["aggressive_close", "conservative_retest"]
  prefer: "retest"

exits:
  tp_levels_pct: [0.004, 0.008, 0.013]
  sl_mode: "vwap_sigma_or_box"

runtime:
  timezone: "Asia/Seoul"
  db_path: "/data/kucoin_signal_bot.db"
  cooldown_minutes: 20
  top_n_by_volume: 120
